#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec 12 10:27:51 2023

@author: leandro
"""

massa = float(input("Introduza a sua massa corporal (kg): "))

altura = float(input("Introduza a sua altura (m): "))

IMC = massa / (altura **2)
print("IMC: ",round(IMC,3))

if IMC < 18.5:
    print("Baixo peso")
elif  IMC  > 18.5 and IMC < 24.0:
    print("Peso normal")
elif  IMC  >=  25 and IMC < 29.9:
     print("Acima do peso") 
elif  IMC  >=  30 and IMC < 34.9:
     print("Obesidade grau 1")        
elif  IMC  >=  35 and IMC < 39.9:
     print("Obesidade grau 2") 
elif  IMC  >=  40:
     print("Obesidade mórbida") 