#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec 12 10:58:59 2023

@author: leandro
"""

# Entrada dos dados

lista = eval(input('Indique a lista de números [a,b,c,d,...... ]: '))

# Calculos

comprimentoDaLista = len(lista)
nPares = 0
for i in lista:
    if i % 2 == 0:
        nPares += 1
nImpares = comprimentoDaLista - nPares

# Apresentação dos resultados

print('A liste possuí ' + str(comprimentoDaLista) + ' elementos ' + ' com  ' +
      str(nPares) + 'números pares e ' + str(nImpares) + ' números ímpares')
print('Percentagens')
print('Percentagem de números pares: ' +
      str(round(100*nPares/comprimentoDaLista, 2)) + ' %')
print('Percentagem de números impares: ' +
      str(round(100*nImpares/comprimentoDaLista, 2)) + ' %')
