#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 18 12:35:59 2023

@author: leandro
"""

numero = int(input('Introduza um número natural: '))

print('Termos pitagóricos: ')
for x in range(1,numero+1):
    for y in range(1,numero+1):
        for z in range(1,numero+1):
            if x**2 + y**2 == z**2:
                texto = '(' + str(x) + ',' + str(y) + ',' +str(z) + ')'
                print(texto.center(30))