#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 18 12:47:00 2023

@author: leandro
"""


a = int(input('Introduza o 1.º número natural: '))
b = int(input('Introduza o 2.º número natural: '))
copiaA = a
copiaB = b

if a < b:
    a, b = b, a
print('*'*30)
print('Algoritmo de Euclides: ')
while b != 0:
    resto = a % b
    print(str(a).center(10) + str(b).center(10) + '/' + str(resto).center(10))
    a, b = b, resto
print('-' * 30)

texto = 'MDC(' + str(copiaA) + ',' + str(copiaB) + ')' + '=' + str(a)
print(texto.center(30))
